### ISSUE TITLE
Wrong link on the correponding odpi.org webpage

### ISSUE THREAD

**Issue by fBedecarrats** [odpi/data-governance#21]
Hi there, it seems that [the webpage referring to this project](https://www.odpi.org/projects/data-governance) on odpi.org website is linking to another repo ([odpi/bi-ai](https://github.com/odpi/bi-ai)) instead of this one.

**Comment by planetf1** [comment]
@jBedecarrats thanks . I suspect the correct destination is the data governance guidance at https://opengovernance.odpi.org - which does then have some links back to the Egeria implementation (and github)

@jmertic @mandy-chessell are you able to get this corrected & for example point at the Egeria info instead? ( I don't have access)

**Comment by jmertic** [comment]
Good catch! Try it now.
